🚧 Update to SDK 33.0.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
👩🏽‍🦯🏤🦹🏻👩🏼‍🏫

Full error log:
Error:  asset 2023-1-2--23-6-14--aa77a89d-1e00-4d03-b62c-988a89a27aaf/main.min.js 929 KiB [emitted] (name: main) 1 related asset
runtime modules 937 bytes 4 modules
javascript modules 217 KiB
  modules by path ./node_modules/ 182 KiB 22 modules
  modules by path ./src/ 35.2 KiB
    modules by path ./src/modules/ 29.5 KiB 10 modules
    modules by path ./src/utils/ 1.31 KiB 3 modules
    modules by path ./src/makers/*.tsx 3.94 KiB 2 modules
    ./src/index.ts 475 bytes [built] [code generated]
json modules 669 KiB
  ./package.json 631 bytes [built] [code generated]
  ./data/czech-first-female-names.json 163 KiB [built] [code generated]
  ./data/czech-first-male-names.json 158 KiB [built] [code generated]
  ./data/czech-last-female-names.json 182 KiB [built] [code generated]
  ./data/czech-last-male-names.json 166 KiB [built] [code generated]

ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-snowflake\snowflake-art-module.tsx
8:16-22
[tsl] ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-snowflake\snowflake-art-module.tsx(8,17)
      TS2531: Object is possibly 'null'.

webpack 5.35.1 compiled with 1 error in 7730 ms

Error:
    at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\random-arts\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
    at Generator.next (<anonymous>)
    at C:\Users\me\work\collboard\random-arts\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\me\work\collboard\random-arts\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
    at Watching.handler (C:\Users\me\work\collboard\random-arts\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
    at C:\Users\me\work\collboard\random-arts\node_modules\webpack\lib\Watching.js:204:9
    at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\random-arts\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\random-arts\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (C:\Users\me\work\collboard\random-arts\node_modules\webpack\lib\Watching.js:201:28)