🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🧎🏻‍♂️👱🏽‍♂️🤘🏾👨🏾‍❤️‍👨🏿

Full error log:
Error:  asset 2022-7-25--0-34-29--5c776776-313b-4fc7-a556-9ed24b20c025/main.min.js 887 KiB [emitted] (name: main) 1 related asset
runtime modules 937 bytes 4 modules
javascript modules 175 KiB
modules by path ./node_modules/ 145 KiB 22 modules
modules by path ./src/ 30.7 KiB
modules by path ./src/modules/ 24.9 KiB 9 modules
modules by path ./src/utils/ 1.3 KiB 3 modules
modules by path ./src/makers/*.tsx 4.12 KiB 2 modules
./src/index.ts 411 bytes [built] [code generated]
json modules 669 KiB
./package.json 632 bytes [built] [code generated]
./data/czech-first-female-names.json 163 KiB [built] [code generated]
./data/czech-first-male-names.json 158 KiB [built] [code generated]
./data/czech-last-female-names.json 182 KiB [built] [code generated]
./data/czech-last-male-names.json 166 KiB [built] [code generated]

ERROR in C:\Users\me\work\collboard\random-arts\src\makers\makeRandomTextToolModule.tsx
./src/makers/makeRandomTextToolModule.tsx 27:16-66
[tsl] ERROR in C:\Users\me\work\collboard\random-arts\src\makers\makeRandomTextToolModule.tsx(27,17)
TS2554: Expected 7 arguments, but got 8.
@ ./src/modules/random-flower-emoji.module.ts 5:35-80
@ ./src/index.ts 6:0-47

ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-color.module.tsx
./src/modules/random-color.module.tsx 48:28-82
[tsl] ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-color.module.tsx(48,29)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/index.ts 4:0-40

ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx
./src/modules/random-czech-name/random-czech-name.module.tsx 87:40-93
[tsl] ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx(87,41)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/index.ts 5:0-63

ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx
./src/modules/random-czech-name/random-czech-name.module.tsx 88:40-96
[tsl] ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx(88,41)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/index.ts 5:0-63

ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx
./src/modules/random-czech-name/random-czech-name.module.tsx 90:44-119
[tsl] ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx(90,45)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'IFontStyleAttributeValue' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
Type 'BehaviorSubject<attribute_value>' is missing the following properties from type 'IFontStyleAttributeValue': bold, italic, underline
@ ./src/index.ts 5:0-63

ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx
./src/modules/random-czech-name/random-czech-name.module.tsx 93:44-119
[tsl] ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx(93,45)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'IFontStyleAttributeValue' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/index.ts 5:0-63

ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx
./src/modules/random-czech-name/random-czech-name.module.tsx 96:44-119
[tsl] ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx(96,45)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'IFontStyleAttributeValue' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/index.ts 5:0-63

ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx
./src/modules/random-czech-name/random-czech-name.module.tsx 99:40-100
[tsl] ERROR in C:\Users\me\work\collboard\random-arts\src\modules\random-czech-name\random-czech-name.module.tsx(99,41)
TS2554: Expected 7 arguments, but got 8.
@ ./src/index.ts 5:0-63

webpack 5.35.1 compiled with 8 errors in 8441 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\random-arts\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\random-arts\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\random-arts\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\random-arts\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\random-arts\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\random-arts\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\random-arts\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\random-arts\node_modules\webpack\lib\Watching.js:201:28)